
name: SonarQube Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: sqa_e21ba8c449eda2f1eddb93723e10b4abaf2c76e3
          sonar-project-name: githubtoken
